const songData = [
  // Pop
  {
    id: 0,
    photo: "assets/song-assets/pop/fortnight - taylorswift.jpg",
    name: "Fortnight",
    artist: "Taylor Swift",
    description:
      "A synth-pop anthem from Taylor Swift. Catchy, emotional, and unforgettable.",
    lyrics: "assets/song-assets/pop/fortnight - taylorswift.txt",
    audio: "assets/song-assets/pop/fortnight - taylorswift (mp3cut.net).m4a",
    genre: "Pop",
  },
  {
    id: 1,
    photo: "assets/song-assets/pop/Sabrina Carpenter Espresso.jpg",
    name: "Espresso",
    artist: "Sabrina Carpenter",
    description:
      "A playful, energetic pop hit with infectious hooks and vibrant vocals.",
    lyrics: "assets/song-assets/pop/Sabrina Carpenter Espresso.txt",
    audio: "assets/song-assets/pop/Sabrina Carpenter Espresso (mp3cut.net).mp3",
    genre: "Pop",
  },
  {
    id: 2,
    photo: "assets/song-assets/pop/blank space - taylorswift.jpg",
    name: "Blank Space",
    artist: "Taylor Swift",
    description: "A pop classic with witty lyrics and a catchy chorus.",
    lyrics: "assets/song-assets/pop/blank space - taylorswift.txt",
    audio: "assets/song-assets/pop/blank space - taylorswift (mp3cut.net).m4a",
    genre: "Pop",
  },
  {
    id: 3,
    photo: "assets/song-assets/pop/Olivia Rodrigo Get Him Back.jpg",
    name: "Get Him Back!",
    artist: "Olivia Rodrigo",
    description: "A bold pop anthem with attitude and energy.",
    lyrics: "assets/song-assets/pop/Olivia Rodrigo Get Him Back.txt",
    audio:
      "assets/song-assets/pop/Olivia Rodrigo Get Him Back (mp3cut.net).mp3",
    genre: "Pop",
  },
  {
    id: 4,
    photo: "assets/song-assets/pop/Lady Gaga & Bruno Mars Die With A Smile.jpg",
    name: "Die With A Smile",
    artist: "Lady Gaga & Bruno Mars",
    description: "A powerful pop duet with uplifting vibes.",
    lyrics:
      "assets/song-assets/pop/Lady Gaga & Bruno Mars Die With A Smile.txt",
    audio:
      "assets/song-assets/pop/Lady Gaga & Bruno Mars Die With A Smile (mp3cut.net).mp3",
    genre: "Pop",
  },
  {
    id: 5,
    photo: "assets/song-assets/pop/Billie Eilish Birds of a Feather.jpg",
    name: "Birds of a Feather",
    artist: "Billie Eilish",
    description: "A dreamy pop track with Billie Eilish's signature style.",
    lyrics: "assets/song-assets/pop/Billie Eilish Birds of a Feather.txt",
    audio:
      "assets/song-assets/pop/Billie Eilish Birds of a Feather (mp3cut.net).mp3",
    genre: "Pop",
  },
  {
    id: 6,
    photo: "assets/song-assets/pop/Beyonce  Texas Hold Em.jpg",
    name: "Texas Hold 'Em",
    artist: "Beyoncé",
    description: "A catchy pop-country crossover from Beyoncé.",
    lyrics: "assets/song-assets/pop/Beyonce Texas Hold Em.txt",
    audio: "assets/song-assets/pop/Beyonce Texas Hold Em (mp3cut.net).m4a",
    genre: "Pop",
  },
  {
    id: 7,
    photo: "assets/song-assets/pop/Beyonce Freedom.jpg",
    name: "Freedom",
    artist: "Beyoncé",
    description: "An empowering pop anthem with strong vocals.",
    lyrics: "assets/song-assets/pop/Beyonce Texas freedom.txt",
    audio: "assets/song-assets/pop/Beyonce Freedom (mp3cut.net).m4a",
    genre: "Pop",
  },
  // R&B
  {
    id: 8,
    photo: "assets/song-assets/rnb/sza saturn.jpg",
    name: "Saturn",
    artist: "SZA",
    description:
      "A soulful R&B track with dreamy vocals and introspective lyrics.",
    lyrics: "assets/song-assets/rnb/sza saturn.txt",
    audio: "assets/song-assets/rnb/SZA - Saturn (mp3cut.net).mp3",
    genre: "R&B",
  },
  {
    id: 9,
    photo: "assets/song-assets/rnb/The Weeknd  Cry for Me.jpg",
    name: "Cry for Me",
    artist: "The Weeknd",
    description:
      "A moody, atmospheric R&B song with The Weeknd's signature style.",
    lyrics: "assets/song-assets/rnb/The Weeknd Cry for Me.txt",
    audio: "assets/song-assets/rnb/The Weeknd  Cry for Me (mp3cut.net).mp3",
    genre: "R&B",
  },
  {
    id: 10,
    photo: "assets/song-assets/rnb/kendrick Lamar Not Like Us.jpeg",
    name: "Not Like Us",
    artist: "Kendrick Lamar",
    description: "A hard-hitting R&B/hip-hop track with sharp lyrics.",
    lyrics: "assets/song-assets/rnb/kendrick Lamar Not Like Us.txt",
    audio: "assets/song-assets/rnb/kendrick Lamar Not Like Us (mp3cut.net).mp3",
    genre: "R&B",
  },
  {
    id: 11,
    photo: "assets/song-assets/rnb/The Weekend Open Hearts.jpeg",
    name: "Open Hearts",
    artist: "The Weekend",
    description: "A heartfelt R&B ballad with smooth vocals.",
    lyrics: "assets/song-assets/rnb/The Weekend Open Hearts.txt",
    audio: "assets/song-assets/rnb/The Weekend Open Hearts (mp3cut.net).mp3",
    genre: "R&B",
  },
  {
    id: 12,
    photo: "assets/song-assets/rnb/SZA Open Arms.jpeg",
    name: "Open Arms",
    artist: "SZA",
    description: "A touching R&B song about vulnerability and love.",
    lyrics: "assets/song-assets/rnb/SZA Open Arms.txt",
    audio: "assets/song-assets/rnb/SZA Open Arms (mp3cut.net).mp3",
    genre: "R&B",
  },
  {
    id: 13,
    photo: "assets/song-assets/rnb/SZA & Kendrick Lamar 30 for 30.jpg",
    name: "30 for 30",
    artist: "SZA & Kendrick Lamar",
    description: "A collaborative R&B track with powerful verses.",
    lyrics: "assets/song-assets/rnb/SZA & Kendrick Lamar 30 for 30.txt",
    audio:
      "assets/song-assets/rnb/SZA & Kendrick Lamar 30 for 30 (mp3cut.net).mp3",
    genre: "R&B",
  },
  {
    id: 14,
    photo: "assets/song-assets/rnb/Kendrick Lamar gloria.jpeg",
    name: "Gloria",
    artist: "Kendrick Lamar",
    description: "A reflective R&B track with deep lyrics.",
    lyrics: "assets/song-assets/rnb/Kendrick Lamar gloria.txt",
    audio: "assets/song-assets/rnb/Kendrick Lamar gloria (mp3cut.net).mp3",
    genre: "R&B",
  },
  {
    id: 15,
    photo: "assets/song-assets/rnb/Giveon Twenties.jpg",
    name: "Twenties",
    artist: "Giveon",
    description: "A smooth R&B song about youth and growth.",
    lyrics: "assets/song-assets/rnb/Giveon Twenties.txt",
    audio: "assets/song-assets/rnb/Giveon Twenties (mp3cut.net).mp3",
    genre: "R&B",
  },
  // K-Pop
  {
    id: 16,
    photo: "assets/song-assets/kpop/aespa Whiplash.jpg",
    name: "Whiplash",
    artist: "aespa",
    description:
      "A high-energy K-Pop track with dynamic beats and powerful vocals.",
    lyrics: "assets/song-assets/kpop/aespa Whiplash.txt",
    audio: "assets/song-assets/kpop/aespa Whiplash (mp3cut.net).mp3",
    genre: "K-Pop",
  },
  {
    id: 17,
    photo: "assets/song-assets/kpop/IVE Rebel Heart.jpg",
    name: "Rebel Heart",
    artist: "IVE",
    description:
      "A bold K-Pop anthem with catchy melodies and strong group vocals.",
    lyrics: "assets/song-assets/kpop/IVE Rebel Heart.txt",
    audio: "assets/song-assets/kpop/IVE Rebel Heart (mp3cut.net).mp3",
    genre: "K-Pop",
  },
  {
    id: 18,
    photo: "assets/song-assets/kpop/Rose & Bruno Mars APT.jpeg",
    name: "APT",
    artist: "Rose & Bruno Mars",
    description: "A catchy K-Pop collaboration with smooth vocals.",
    lyrics: "assets/song-assets/kpop/Rose & Bruno Mars APT.txt",
    audio: "assets/song-assets/kpop/Rose & Bruno Mars APT (mp3cut.net).mp3",
    genre: "K-Pop",
  },
  {
    id: 19,
    photo: "assets/song-assets/kpop/KISS OF LIFE Igloo.jpg",
    name: "Igloo",
    artist: "KISS OF LIFE",
    description: "A cool K-Pop track with unique style and vocals.",
    lyrics: "assets/song-assets/kpop/KISS OF LIFE Igloo.txt",
    audio: "assets/song-assets/kpop/KISS OF LIFE Igloo (mp3cut.net).mp3",
    genre: "K-Pop",
  },
  {
    id: 20,
    photo: "assets/song-assets/kpop/GOT7 Python.jpeg",
    name: "Python",
    artist: "GOT7",
    description: "A dynamic K-Pop song with energetic beats.",
    lyrics: "assets/song-assets/kpop/GOT7 Python.txt",
    audio: "assets/song-assets/kpop/GOT7 Python (mp3cut.net).mp3",
    genre: "K-Pop",
  },
  {
    id: 21,
    photo:
      "assets/song-assets/kpop/GDragon ft. Taeyang & Daesung Home Sweet Home.jpg",
    name: "Home Sweet Home",
    artist: "GDragon ft. Taeyang & Daesung",
    description: "A heartfelt K-Pop collaboration with memorable melodies.",
    lyrics:
      "assets/song-assets/kpop/GDragon ft. Taeyang & Daesung Home Sweet Home.txt",
    audio: "assets/song-assets/kpop/GDragon ft (mp3cut.net).mp3",
    genre: "K-Pop",
  },
  {
    id: 22,
    photo: "assets/song-assets/kpop/BOYNEXTDOOR If I Say, I Love You.jpg",
    name: "If I Say, I Love You",
    artist: "BOYNEXTDOOR",
    description: "A sweet K-Pop song about love and confession.",
    lyrics: "assets/song-assets/kpop/BOYNEXTDOOR If I Say, I Love You.txt",
    audio:
      "assets/song-assets/kpop/BOYNEXTDOOR If I Say, I Love You (mp3cut.net).mp3",
    genre: "K-Pop",
  },
  {
    id: 23,
    photo: "assets/song-assets/kpop/BABYMONSTER Drip.jpg",
    name: "Drip",
    artist: "BABYMONSTER",
    description: "A bold K-Pop track with attitude and style.",
    lyrics: "assets/song-assets/kpop/BABYMONSTER Drip.txt",
    audio: "assets/song-assets/kpop/BABYMONSTER Drip (mp3cut.net).mp3",
    genre: "K-Pop",
  },
];
window.songData = songData;
